import React, { useRef } from "react";

import Head from "next/head";

import { Card, Container, Grid } from "@mui/material";

import gsap from "gsap";

import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

// Components
import HomeOutputs from "../components/HomeOutputs";
import Highlights from "../components/Highlights";
import PlaySvg from "../components/PlaySvg";

// Sections
import Banner from "../components/Banner/Banner";
import CampaignVideos from "../components/CampaignVideos/CampaignVideos";

import useSnoothScroll from "@/hook/use-smooth-scroll";

import homeStyle from "@/styles/home.module.scss";
import SplitTextComponent from "../components/SplitText/SplitText";

import { useIsomorphicLayoutEffect } from "@/hook";

import ArrowOutwardIcon from "@mui/icons-material/ArrowOutward";

import MapComponent from "../components/MapData/MapComponent";

import ImpactNumbers from "../components/ImpactsNumber";
import { ActionButton } from "@/components/ActonButton";

let partnersData = [
  {
    title: "",
    logo: "./imp_logo/Creasion logoo-01.png",
    link: "",
    type: "1",
  },
  {
    title: "",
    logo: "./imp_logo/PLEASE-logo.png",
    link: "",
    type: "1",
  },
  {
    title: "",
    logo: "./imp_logo/SACEP logo-High Resolution.png",
    link: "",
    type: "1",
  },
  {
    title: "",
    logo: "./imp_logo/unops-logo.png",
    link: "",
    type: "1",
  },
  {
    title: "",
    logo: "./imp_logo/The_World_Bank_logo.svg (2).png",
    link: "",
    type: "1",
  },
];

let collabPartner = [
  {
    title: "",
    logo: "./imp_logo/Municipalities/1 Bhartpur.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/2 Lalitpur.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/3 hetauda.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/4 bardi.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/5 ichha.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/6 gajuri.png",
    link: "",
    type: "2",
  },
  {
    title: "",
    logo: "./imp_logo/Municipalities/7 Golanjor.png",
    link: "",
    type: "2",
  },
];

export default function Home() {
  gsap.registerPlugin(ScrollTrigger);
  const projectBoxRef = useRef(null);
  const projectBackgroundRef = useRef(null);
  const projectSummaryRef = useRef(null);

  useIsomorphicLayoutEffect(() => {
    const gsapCtx = gsap.context(() => {
      gsap.to(projectBackgroundRef.current, {
        scrollTrigger: {
          trigger: projectBoxRef.current,
          pin: projectBackgroundRef.current,
          pinSpacing: false,
          end: "bottom bottom",
        },
      });

      gsap.to(projectSummaryRef.current, {
        scrollTrigger: {
          trigger: projectBoxRef.current,
          pin: projectSummaryRef.current,
          start: "top 10%",
          pinSpacing: false,
          end: "bottom bottom",
        },
      });

      ScrollTrigger.refresh();
    });

    if (window.innerWidth < 900) {
      gsapCtx.revert();
    }

    return () => gsapCtx.revert();
  });
  return (
    <>
      <Head>
        <title>CAP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="./1a3b9e8c-88a0-449a-8c74-0f58aef99fe6.png"
        />
        <meta property="og:image:width" content="640" />
        <meta property="og:image:height" content="442" />
      </Head>

      <Banner />

      {/* <section className={homeStyle.intro} id="intro">
        <Container maxWidth="lg">
          <SplitTextComponent />
        </Container>
      </section> */}

      <section className={homeStyle.numanim}>
        <Container maxWidth="lg">
          <h2 style={{ backgroundImage: `url(./plastic-pollution-beach.jpg)` }}>
            20 Kilo
          </h2>
          <h3>tons Plastic Leakage per year</h3>
          <p>
            In Nepal alone, an estimated 20 Kilo Tons of plastic leak into the
            environment each year, with rivers bearing the brunt of this
            ecological burden. As plastic consumption rises and efficient waste
            management remains elusive, the urgency to address this issue
            intensifies. . Our project operates on the premise that we can
            prevent plastic leakage into river systems by focusing on two
            critical pillars: strengthening plastic waste collection mechanisms
            and establishing recycling facilities to impart value to collected
            plastic waste.
          </p>
          <p>
            "Urgent action is needed to curb plastic waste that pollutes the
            land and flows into oceans. It is killing wildlife, damaging
            ecosystems, clogging drainage systems, and harming fisheries and
            tourism which are key sources of the jobs on which the people and
            economies of South Asia depend."
          </p>
          <span> - THE WORLD BANK </span>
        </Container>
      </section>

      <section className={homeStyle.map_box}>
        <MapComponent />
      </section>

      {/* <section className={homeStyle.ft_video}>
        <Container maxWidth="lg">
          <div className={homeStyle.video_container}>
            <img
              src="./quiet-issue-underwater-plastics-float-blue-sea.jpg"
              alt="bottle"
            />
            <div className={homeStyle.playbtn}>
              <PlaySvg />
              <h6>Plastic-Free Rivers and Seas for South Asia</h6>
            </div>
          </div>
        </Container>
      </section> */}

      <section className={homeStyle.outputs} ref={projectBoxRef}>
        <div
          ref={projectBackgroundRef}
          className={homeStyle.outputs_background}
          style={{ backgroundImage: "url(./guy-lake-makes-fire.jpg)" }}
        ></div>
        <Container maxWidth="xl">
          <Grid container spacing={3}>
            <Grid item md={5}>
              <div ref={projectSummaryRef}>
                <h2>Project Outputs</h2>
                <p>
                  Project CAP has developed an integrated plastic collection
                  model involving marginalized communities, informal waste
                  workers, and youth groups, while emphasizing dignity of labor
                  through training. Additionally, an inclusive recycling network
                  engages marginalized women, waste workers, and key
                  stakeholders, adding value to collected plastic waste. Through
                  education and advocacy, stakeholders including private waste
                  enterprises and governmental bodies support an enabling
                  environment for plastic waste management. Efficient knowledge
                  dissemination aids national and regional replication, ensuring
                  sustainability.
                </p>
              </div>
            </Grid>
          </Grid>
          <HomeOutputs />
        </Container>
      </section>

      <section className={homeStyle.impacts}>
        <Container maxWidth="xl">
          <Grid container spacing={4}>
            <Grid item md={6}>
              <h2>Project Impacts</h2>
            </Grid>
            <Grid item md={3}>
              <p>
                Project CAP operates across six municipalities in Nepal,
                strategically positioned along four major river basins, where
                the impact of plastic leakage is most keenly felt.
              </p>
            </Grid>
            <Grid item md={3}>
              <p>
                A collaborative initiative focused on the prevention of plastic
                leakages in water resources, empowering individuals and
                organizations to make a lasting impact on environmental
                conservation.
              </p>
            </Grid>
          </Grid>

          <ImpactNumbers />
        </Container>
      </section>

      <CampaignVideos />

      <section className={homeStyle.highlights}>
        <Container maxWidth="md" style={{ textAlign: "center" }}>
          <h2>Project Highlights</h2>
          <p>
            We curate engaging blogs, deliver up-to-date news on successful
            initiatives, conduct impactful research, and host dynamic events to
            empower governments and communities in adopting nature-based
            solutions for sustainable economic growth and development.
          </p>
        </Container>

        <Highlights />
      </section>

      <section
        className={homeStyle.partners}
        style={{
          backgroundImage: `url('./plastic-waste-pollution-ocean-plastic-bottle-floating-ocean-generative-ai.jpg')`,
        }}
      >
        <Container maxWidth="xl">
          <Grid container spacing={2} style={{ marginTop: "32px" }}>
            <Grid item md={6}></Grid>
            <Grid item md={6}>
              <h2>Implementing Partners</h2>
              <p>
                Project CAP operates across six municipalities in Nepal,
                strategically positioned along four major river basins, where
                the impact of plastic leakage is most keenly felt. A
                collaborative initiative focused on the prevention of plastic
                leakages in water resources, empowering individuals and
                organizations to make a lasting impact on environmental
                conservation.
              </p>
              <Grid
                container
                spacing={3}
                style={{
                  marginTop: "0px",
                  alignItems: "center",
                  textAlign: "center",
                }}
              >
                {partnersData.map((val, index) => {
                  return (
                    <Grid item md={4} sm={6} xs={6} key={index}>
                      <div className={homeStyle.partners_logo}>
                        <img src={val.logo} alt="" />
                      </div>
                    </Grid>
                  );
                })}
              </Grid>

              <h5>In Collaboration with</h5>

              <Grid
                container
                spacing={3}
                style={{
                  marginTop: "0px",
                  alignItems: "center",
                  textAlign: "center",
                }}
              >
                {collabPartner.map((val, index) => {
                  return (
                    <Grid item md={4} sm={6} xs={6} key={index}>
                      <div className={homeStyle.partners_logo}>
                        <img src={val.logo} alt="" />
                      </div>
                    </Grid>
                  );
                })}
              </Grid>
            </Grid>
          </Grid>
        </Container>
      </section>

      <section className={homeStyle.grievance}>
        <Container maxWidth="lg">
          <h2>Grievance Mechanism</h2>
          <p>
            Managed by the Project Implementation Unit, the Project Cap
            (Collaborative Approach for Preventing Plastic Leakages in Rivers)
            is committed to upholding the highest standards of integrity and we
            have a zero-tolerance policy regarding any instances of misconduct.
          </p>

          <ActionButton title={"Grievance "} style={"dark"} />
        </Container>
      </section>
    </>
  );
}
